#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use TetaFramework\Commands\HelloCommand;
use TetaFramework\Commands\HelpCommand;
use TetaFramework\Commands\MakeAllCommand;
use TetaFramework\Commands\MigrateCommand;
use TetaFramework\Commands\ServeCommand;
use TetaFramework\Commands\MakeModelCommand;
use TetaFramework\Commands\MakeControllerCommand;
use TetaFramework\Commands\MakeViewCommand;
use TetaFramework\Commands\RunTestsCommand;

$application = new Application();

// Registrar comandos aquí
$application->add(new HelloCommand());
$application->add(new MigrateCommand());
$application->add(new ServeCommand());
$application->add(new MakeModelCommand());
$application->add(new MakeControllerCommand());
$application->add(new MakeViewCommand());
$application->add(new MakeAllCommand());
$application->add(new RunTestsCommand());
$application->add(new HelpCommand());

$application->run();
