#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use TetaFramework\Commands\HelloCommand;
use TetaFramework\Commands\MigrateCommand;
use TetaFramework\Commands\ServeCommand;

$application = new Application();

// Registrar comandos aquí
$application->add(new HelloCommand());
$application->add(new MigrateCommand());
$application->add(new ServeCommand());

$application->run();
